version: "3.7"
services:
  minio:
    build: .
    hostname: bucket.minio
    environment:
       - MINIO_ROOT_USER=minio
       # password needs to be at least 8 chars
       - MINIO_ROOT_PASSWORD=miniominio
       - MINIO_BUCKET_NAME=bucket
       # should be set to the last part of hostname
       - MINIO_DOMAIN=minio
    ports:
      - 9000:9000
